import React, { useState, useEffect } from 'react';
import { matchService, UPLOAD_URL } from '../services/api';
import { useToast } from '../context/ToastContext';
import { 
  Sparkles, AlertCircle, HelpCircle, MapPin, 
  Calendar, Phone, Mail, User, ShieldCheck, ChevronRight
} from 'lucide-react';

export const Matches = () => {
  const { showToast } = useToast();
  const [matches, setMatches] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeContactId, setActiveContactId] = useState(null); // ID of match showing contact info

  useEffect(() => {
    const fetchMatches = async () => {
      try {
        const response = await matchService.getMatches();
        if (response.success) {
          setMatches(response.matches);
        } else {
          showToast('Failed to load match results.', 'error');
        }
      } catch (error) {
        console.error('Error fetching matches:', error);
        showToast('Error fetching matches.', 'error');
      } finally {
        setLoading(false);
      }
    };

    fetchMatches();
  }, [showToast]);

  const getScoreColor = (score) => {
    if (score >= 80) return 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20';
    if (score >= 55) return 'text-amber-400 bg-amber-500/10 border-amber-500/20';
    return 'text-indigo-400 bg-indigo-500/10 border-indigo-500/20';
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  if (loading) {
    return (
      <div className="space-y-6 animate-pulse">
        {[1, 2, 3].map((n) => (
          <div key={n} className="h-64 bg-slate-900/60 rounded-3xl border border-slate-800/60"></div>
        ))}
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div>
        <h1 className="text-xl md:text-2xl font-extrabold text-slate-100 flex items-center gap-2">
          Item Matches <Sparkles className="w-5 h-5 text-amber-400 animate-pulse" />
        </h1>
        <p className="text-xs text-slate-400">
          Smart matching results generated by the similarity scanning engine
        </p>
      </div>

      {matches.length === 0 ? (
        <div className="text-center py-20 bg-slate-905 border border-slate-855 rounded-3xl border-dashed">
          <AlertCircle className="w-12 h-12 text-slate-500 mx-auto mb-4" />
          <h3 className="text-lg font-bold text-slate-350">No Matches Identified Yet</h3>
          <p className="text-slate-500 text-sm mt-1 max-w-sm mx-auto">
            Our system scans reports automatically. Ensure you fill descriptive details in your lost or found forms to increase match chances.
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {matches.map((match) => {
            const scoreClass = getScoreColor(match.match_score);
            const isContactActive = activeContactId === match.match_id;

            return (
              <div 
                key={match.match_id}
                className="bg-slate-905 border border-slate-855 rounded-3xl overflow-hidden shadow-xl"
              >
                {/* Match Header Panel */}
                <div className="bg-slate-900 px-6 py-4 flex flex-wrap items-center justify-between gap-4 border-b border-slate-850">
                  <div className="flex items-center gap-2">
                    <span className={`text-xs font-black px-3 py-1 rounded-full border tracking-wider ${scoreClass}`}>
                      {match.match_score}% MATCH
                    </span>
                    <span className="text-[10px] text-slate-400 font-medium">
                      Identified on {formatDate(match.match_date)}
                    </span>
                  </div>
                  
                  <button
                    onClick={() => setActiveContactId(isContactActive ? null : match.match_id)}
                    className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold py-2 px-4 rounded-xl shadow transition-colors cursor-pointer"
                  >
                    {isContactActive ? 'Hide Contact Info' : 'Contact Party'}
                  </button>
                </div>

                {/* Split comparison panels */}
                <div className="grid grid-cols-1 md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-slate-850">
                  
                  {/* Left Column: Lost Item */}
                  <div className="p-6 space-y-4">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-[10px] font-black uppercase tracking-widest px-2 py-0.5 bg-rose-500/10 border border-rose-500/20 text-rose-400 rounded-lg">
                        Lost Report
                      </span>
                      <span className="text-[11px] text-slate-500 font-semibold">{match.lost_item.category}</span>
                    </div>

                    <div className="flex gap-4">
                      {/* Image Thumbnail */}
                      <div className="w-20 h-20 bg-slate-950 rounded-xl border border-slate-850 overflow-hidden flex-shrink-0 flex items-center justify-center">
                        {match.lost_item.image ? (
                          <img 
                            src={`${UPLOAD_URL}/${match.lost_item.image}`} 
                            alt={match.lost_item.item_name} 
                            className="w-full h-full object-cover"
                          />
                        ) : (
                          <HelpCircle className="w-6 h-6 text-slate-650" />
                        )}
                      </div>

                      {/* Info */}
                      <div className="space-y-1">
                        <h4 className="font-bold text-slate-200 text-sm">{match.lost_item.item_name}</h4>
                        <p className="text-xs text-slate-400 line-clamp-2 leading-relaxed">
                          {match.lost_item.description}
                        </p>
                      </div>
                    </div>

                    <div className="flex items-center gap-y-1 gap-x-4 text-[11px] text-slate-400 pt-2">
                      <span className="flex items-center gap-1">
                        <MapPin className="w-3.5 h-3.5 text-slate-550 flex-shrink-0" />
                        <span>{match.lost_item.location}</span>
                      </span>
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3.5 h-3.5 text-slate-550 flex-shrink-0" />
                        <span>{formatDate(match.lost_item.date_lost)}</span>
                      </span>
                    </div>
                  </div>

                  {/* Right Column: Found Item */}
                  <div className="p-6 space-y-4">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-[10px] font-black uppercase tracking-widest px-2 py-0.5 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-lg">
                        Found Report
                      </span>
                      <span className="text-[11px] text-slate-500 font-semibold">{match.found_item.category}</span>
                    </div>

                    <div className="flex gap-4">
                      {/* Image Thumbnail */}
                      <div className="w-20 h-20 bg-slate-950 rounded-xl border border-slate-850 overflow-hidden flex-shrink-0 flex items-center justify-center">
                        {match.found_item.image ? (
                          <img 
                            src={`${UPLOAD_URL}/${match.found_item.image}`} 
                            alt={match.found_item.item_name} 
                            className="w-full h-full object-cover"
                          />
                        ) : (
                          <HelpCircle className="w-6 h-6 text-slate-650" />
                        )}
                      </div>

                      {/* Info */}
                      <div className="space-y-1">
                        <h4 className="font-bold text-slate-200 text-sm">{match.found_item.item_name}</h4>
                        <p className="text-xs text-slate-400 line-clamp-2 leading-relaxed">
                          {match.found_item.description}
                        </p>
                      </div>
                    </div>

                    <div className="flex items-center gap-y-1 gap-x-4 text-[11px] text-slate-400 pt-2">
                      <span className="flex items-center gap-1">
                        <MapPin className="w-3.5 h-3.5 text-slate-550 flex-shrink-0" />
                        <span>{match.found_item.location}</span>
                      </span>
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3.5 h-3.5 text-slate-550 flex-shrink-0" />
                        <span>{formatDate(match.found_item.date_found)}</span>
                      </span>
                    </div>
                  </div>

                </div>

                {/* Contact Drawer Panel (Renders slide down when contact active) */}
                {isContactActive && (
                  <div className="bg-slate-950/80 border-t border-slate-850 px-6 py-5 grid grid-cols-1 md:grid-cols-2 gap-4 animate-slide-down">
                    
                    {/* Lost Reporter Contact details */}
                    <div className="p-4 bg-slate-900 border border-slate-800 rounded-2xl space-y-3">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1">
                        <User className="w-3.5 h-3.5 text-indigo-400" />
                        <span>Lost Owner Details</span>
                      </span>
                      <div className="text-xs space-y-1.5 text-slate-300">
                        <p className="font-bold text-slate-100">{match.lost_item.owner.name}</p>
                        <p className="flex items-center gap-1.5">
                          <Mail className="w-3.5 h-3.5 text-slate-500" />
                          <a href={`mailto:${match.lost_item.owner.email}`} className="text-indigo-400 hover:underline">{match.lost_item.owner.email}</a>
                        </p>
                        <p className="flex items-center gap-1.5">
                          <Phone className="w-3.5 h-3.5 text-slate-500" />
                          <a href={`tel:${match.lost_item.owner.phone}`} className="text-indigo-400 hover:underline">{match.lost_item.owner.phone}</a>
                        </p>
                      </div>
                    </div>

                    {/* Found Finder Contact details */}
                    <div className="p-4 bg-slate-900 border border-slate-800 rounded-2xl space-y-3">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1">
                        <ShieldCheck className="w-3.5 h-3.5 text-indigo-400" />
                        <span>Finder / Claim Details</span>
                      </span>
                      <div className="text-xs space-y-1.5 text-slate-300">
                        <p className="font-bold text-slate-100">{match.found_item.finder.name}</p>
                        <p className="flex items-center gap-1.5">
                          <Mail className="w-3.5 h-3.5 text-slate-500" />
                          <a href={`mailto:${match.found_item.finder.email}`} className="text-indigo-400 hover:underline">{match.found_item.finder.email}</a>
                        </p>
                        <p className="flex items-center gap-1.5">
                          <Phone className="w-3.5 h-3.5 text-slate-500" />
                          <a href={`tel:${match.found_item.finder.phone}`} className="text-indigo-400 hover:underline">{match.found_item.finder.phone}</a>
                        </p>
                      </div>
                    </div>

                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
export default Matches;
