import React, { useState, useEffect } from 'react';
import { matchService, UPLOAD_URL } from '../services/api';
import { useToast } from '../context/ToastContext';
import { 
  Sparkles, AlertCircle, HelpCircle, MapPin, 
  Calendar, Phone, Mail, User, ShieldCheck, ChevronRight, Check, AlertTriangle, Activity
} from 'lucide-react';

export const Matches = () => {
  const { showToast } = useToast();
  const [matches, setMatches] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeContactId, setActiveContactId] = useState(null); // ID of match showing contact info
  const [aiAnalysis, setAiAnalysis] = useState({}); // Stores AI verify analysis by match_id
  const [activeAIVerifyId, setActiveAIVerifyId] = useState(null); // ID of match showing AI diagnostics

  useEffect(() => {
    const fetchMatches = async () => {
      try {
        const response = await matchService.getMatches();
        if (response.success) {
          setMatches(response.matches);
        } else {
          showToast('Failed to load match results.', 'error');
        }
      } catch (error) {
        console.error('Error fetching matches:', error);
        showToast('Error fetching matches.', 'error');
      } finally {
        setLoading(false);
      }
    };

    fetchMatches();
  }, [showToast]);

  const handleRunAIVerify = async (matchId, lostItemId, foundItemId) => {
    if (activeAIVerifyId === matchId) {
      setActiveAIVerifyId(null);
      return;
    }

    setActiveAIVerifyId(matchId);

    if (aiAnalysis[matchId]?.data) return;

    setAiAnalysis(prev => ({
      ...prev,
      [matchId]: { loading: true, data: null, error: null }
    }));

    try {
      const response = await matchService.verifyMatchWithAI(lostItemId, foundItemId);
      if (response.success) {
        setAiAnalysis(prev => ({
          ...prev,
          [matchId]: { loading: false, data: response.analysis, error: null }
        }));
      } else {
        setAiAnalysis(prev => ({
          ...prev,
          [matchId]: { loading: false, data: null, error: 'AI Verification failed.' }
        }));
        showToast('AI Verification failed.', 'error');
      }
    } catch (error) {
      console.error('AI verification error:', error);
      setAiAnalysis(prev => ({
        ...prev,
        [matchId]: { loading: false, data: null, error: 'Error calling AI comparison service.' }
      }));
      showToast('Error running AI verification.', 'error');
    }
  };

  const getScoreColor = (score) => {
    if (score >= 80) return 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20';
    if (score >= 55) return 'text-amber-400 bg-amber-500/10 border-amber-500/20';
    return 'text-indigo-400 bg-indigo-500/10 border-indigo-500/20';
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  if (loading) {
    return (
      <div className="space-y-6 animate-pulse">
        {[1, 2, 3].map((n) => (
          <div key={n} className="h-64 bg-slate-900/60 rounded-3xl border border-slate-800/60"></div>
        ))}
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div>
        <h1 className="text-xl md:text-2xl font-extrabold text-slate-100 flex items-center gap-2">
          Item Matches <Sparkles className="w-5 h-5 text-amber-400 animate-pulse" />
        </h1>
        <p className="text-xs text-slate-400">
          Smart matching results generated by the similarity scanning engine
        </p>
      </div>

      {matches.length === 0 ? (
        <div className="text-center py-20 bg-slate-905 border border-slate-855 rounded-3xl border-dashed">
          <AlertCircle className="w-12 h-12 text-slate-500 mx-auto mb-4" />
          <h3 className="text-lg font-bold text-slate-350">No Matches Identified Yet</h3>
          <p className="text-slate-500 text-sm mt-1 max-w-sm mx-auto">
            Our system scans reports automatically. Ensure you fill descriptive details in your lost or found forms to increase match chances.
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {matches.map((match) => {
            const scoreClass = getScoreColor(match.match_score);
            const isContactActive = activeContactId === match.match_id;

            return (
              <div 
                key={match.match_id}
                className="bg-slate-905 border border-slate-855 rounded-3xl overflow-hidden shadow-xl"
              >
                {/* Match Header Panel */}
                <div className="bg-slate-900 px-6 py-4 flex flex-wrap items-center justify-between gap-4 border-b border-slate-850">
                  <div className="flex items-center gap-2">
                    <span className={`text-xs font-black px-3 py-1 rounded-full border tracking-wider ${scoreClass}`}>
                      {match.match_score}% MATCH
                    </span>
                    <span className="text-[10px] text-slate-400 font-medium">
                      Identified on {formatDate(match.match_date)}
                    </span>
                  </div>
                  
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => handleRunAIVerify(match.match_id, match.lost_item.id, match.found_item.id)}
                      className="bg-purple-650 hover:bg-purple-600 text-white text-xs font-bold py-2 px-4 rounded-xl shadow transition-colors cursor-pointer flex items-center gap-1.5"
                    >
                      <Sparkles className="w-3.5 h-3.5 text-amber-350 animate-pulse" />
                      <span>{activeAIVerifyId === match.match_id ? 'Hide AI Verdict' : 'Verify with AI'}</span>
                    </button>

                    <button
                      onClick={() => setActiveContactId(isContactActive ? null : match.match_id)}
                      className="bg-indigo-650 hover:bg-indigo-600 text-white text-xs font-bold py-2 px-4 rounded-xl shadow transition-colors cursor-pointer"
                    >
                      {isContactActive ? 'Hide Contact Info' : 'Contact Party'}
                    </button>
                  </div>
                </div>

                {/* Split comparison panels */}
                <div className="grid grid-cols-1 md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-slate-850">
                  
                  {/* Left Column: Lost Item */}
                  <div className="p-6 space-y-4">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-[10px] font-black uppercase tracking-widest px-2 py-0.5 bg-rose-500/10 border border-rose-500/20 text-rose-400 rounded-lg">
                        Lost Report
                      </span>
                      <span className="text-[11px] text-slate-500 font-semibold">{match.lost_item.category}</span>
                    </div>

                    <div className="flex gap-4">
                      {/* Image Thumbnail */}
                      <div className="w-20 h-20 bg-slate-950 rounded-xl border border-slate-850 overflow-hidden flex-shrink-0 flex items-center justify-center">
                        {match.lost_item.image ? (
                          <img 
                            src={`${UPLOAD_URL}/${match.lost_item.image}`} 
                            alt={match.lost_item.item_name} 
                            className="w-full h-full object-cover"
                          />
                        ) : (
                          <HelpCircle className="w-6 h-6 text-slate-650" />
                        )}
                      </div>

                      {/* Info */}
                      <div className="space-y-1">
                        <h4 className="font-bold text-slate-200 text-sm">{match.lost_item.item_name}</h4>
                        <p className="text-xs text-slate-400 line-clamp-2 leading-relaxed">
                          {match.lost_item.description}
                        </p>
                      </div>
                    </div>

                    <div className="flex items-center gap-y-1 gap-x-4 text-[11px] text-slate-400 pt-2">
                      <span className="flex items-center gap-1">
                        <MapPin className="w-3.5 h-3.5 text-slate-550 flex-shrink-0" />
                        <span>{match.lost_item.location}</span>
                      </span>
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3.5 h-3.5 text-slate-550 flex-shrink-0" />
                        <span>{formatDate(match.lost_item.date_lost)}</span>
                      </span>
                    </div>
                  </div>

                  {/* Right Column: Found Item */}
                  <div className="p-6 space-y-4">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-[10px] font-black uppercase tracking-widest px-2 py-0.5 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-lg">
                        Found Report
                      </span>
                      <span className="text-[11px] text-slate-500 font-semibold">{match.found_item.category}</span>
                    </div>

                    <div className="flex gap-4">
                      {/* Image Thumbnail */}
                      <div className="w-20 h-20 bg-slate-950 rounded-xl border border-slate-850 overflow-hidden flex-shrink-0 flex items-center justify-center">
                        {match.found_item.image ? (
                          <img 
                            src={`${UPLOAD_URL}/${match.found_item.image}`} 
                            alt={match.found_item.item_name} 
                            className="w-full h-full object-cover"
                          />
                        ) : (
                          <HelpCircle className="w-6 h-6 text-slate-650" />
                        )}
                      </div>

                      {/* Info */}
                      <div className="space-y-1">
                        <h4 className="font-bold text-slate-200 text-sm">{match.found_item.item_name}</h4>
                        <p className="text-xs text-slate-400 line-clamp-2 leading-relaxed">
                          {match.found_item.description}
                        </p>
                      </div>
                    </div>

                    <div className="flex items-center gap-y-1 gap-x-4 text-[11px] text-slate-400 pt-2">
                      <span className="flex items-center gap-1">
                        <MapPin className="w-3.5 h-3.5 text-slate-550 flex-shrink-0" />
                        <span>{match.found_item.location}</span>
                      </span>
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3.5 h-3.5 text-slate-550 flex-shrink-0" />
                        <span>{formatDate(match.found_item.date_found)}</span>
                      </span>
                    </div>
                  </div>

                </div>

                {/* AI Diagnostics Drawer Panel */}
                {activeAIVerifyId === match.match_id && (() => {
                  const state = aiAnalysis[match.match_id];
                  if (!state) return null;

                  if (state.loading) {
                    return (
                      <div className="bg-indigo-500/5 border-t border-b border-slate-850 px-6 py-8 flex flex-col items-center justify-center space-y-3">
                        <Activity className="w-6 h-6 text-purple-500 animate-spin" />
                        <span className="text-xs font-bold text-slate-350 animate-pulse">Running AI Semantic Cross-Examination...</span>
                        <span className="text-[10px] text-slate-500">Retrieving item data and compiling similarity analysis</span>
                      </div>
                    );
                  }

                  if (state.error) {
                    return (
                      <div className="bg-rose-500/5 border-t border-b border-slate-850 px-6 py-6 flex items-center gap-3">
                        <AlertTriangle className="w-5 h-5 text-rose-500 flex-shrink-0" />
                        <span className="text-xs text-rose-600 font-semibold">{state.error}</span>
                      </div>
                    );
                  }

                  const analysis = state.data;
                  if (!analysis) return null;

                  let verdictClass = "text-indigo-650 bg-indigo-500/10 border-indigo-500/20";
                  let verdictLabel = "Unlikely Match";
                  if (analysis.match_verdict === "highly_likely") {
                    verdictClass = "text-emerald-655 bg-emerald-500/10 border-emerald-500/20";
                    verdictLabel = "Highly Likely Match";
                  } else if (analysis.match_verdict === "possible") {
                    verdictClass = "text-amber-655 bg-amber-500/10 border-amber-500/20";
                    verdictLabel = "Possible Match";
                  }

                  return (
                    <div className="bg-gradient-to-br from-indigo-500/5 to-purple-500/5 border-t border-b border-slate-850 px-6 py-5 space-y-4 animate-slide-down">
                      <div className="flex flex-wrap items-center justify-between gap-3">
                        <div className="flex items-center gap-2">
                          <Sparkles className="w-4 h-4 text-amber-500" />
                          <span className="text-xs font-black text-slate-350 tracking-wide uppercase">AI Deep Diagnosis Report</span>
                        </div>
                        
                        <div className="flex items-center gap-2">
                          <span className={`text-[10px] font-black px-2.5 py-0.5 rounded-full border ${verdictClass}`}>
                            {verdictLabel}
                          </span>
                          <span className="text-[10px] font-bold text-slate-500 bg-slate-950 px-2.5 py-0.5 rounded">
                            {analysis.similarity_score}% SIMILARITY
                          </span>
                        </div>
                      </div>

                      <div className="text-xs text-slate-600 leading-relaxed bg-white border border-slate-700/30 p-4 rounded-2xl shadow-sm">
                        {analysis.analysis_details}
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="bg-emerald-500/5 border border-emerald-500/10 p-3.5 rounded-2xl space-y-2">
                          <span className="text-[10px] font-extrabold text-emerald-600 uppercase tracking-wider flex items-center gap-1">
                            <Check className="w-3.5 h-3.5" />
                            <span>Matching Features</span>
                          </span>
                          {analysis.matching_points?.length > 0 ? (
                            <ul className="text-xs text-slate-600 space-y-1.5 pl-1">
                              {analysis.matching_points.map((pt, i) => (
                                <li key={i} className="flex items-start gap-1.5">
                                  <span className="text-emerald-500 font-bold mt-0.5">•</span>
                                  <span>{pt}</span>
                                </li>
                              ))}
                            </ul>
                          ) : (
                            <p className="text-[11px] text-slate-500 italic">No specific matching features noted.</p>
                          )}
                        </div>

                        <div className="bg-amber-500/5 border border-amber-500/10 p-3.5 rounded-2xl space-y-2">
                          <span className="text-[10px] font-extrabold text-amber-600 uppercase tracking-wider flex items-center gap-1">
                            <AlertTriangle className="w-3.5 h-3.5" />
                            <span>Potential Discrepancies</span>
                          </span>
                          {analysis.discrepancies?.length > 0 ? (
                            <ul className="text-xs text-slate-600 space-y-1.5 pl-1">
                              {analysis.discrepancies.map((pt, i) => (
                                <li key={i} className="flex items-start gap-1.5">
                                  <span className="text-amber-500 font-bold mt-0.5">•</span>
                                  <span>{pt}</span>
                                </li>
                              ))}
                            </ul>
                          ) : (
                            <p className="text-[11px] text-slate-500 italic">No obvious discrepancies found.</p>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })()}

                {/* Contact Drawer Panel (Renders slide down when contact active) */}
                {isContactActive && (
                  <div className="bg-slate-950/80 border-t border-slate-850 px-6 py-5 grid grid-cols-1 md:grid-cols-2 gap-4 animate-slide-down">
                    
                    {/* Lost Reporter Contact details */}
                    <div className="p-4 bg-slate-900 border border-slate-800 rounded-2xl space-y-3">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1">
                        <User className="w-3.5 h-3.5 text-indigo-400" />
                        <span>Lost Owner Details</span>
                      </span>
                      <div className="text-xs space-y-1.5 text-slate-300">
                        <p className="font-bold text-slate-100">{match.lost_item.owner.name}</p>
                        <p className="flex items-center gap-1.5">
                          <Mail className="w-3.5 h-3.5 text-slate-500" />
                          <a href={`mailto:${match.lost_item.owner.email}`} className="text-indigo-400 hover:underline">{match.lost_item.owner.email}</a>
                        </p>
                        <p className="flex items-center gap-1.5">
                          <Phone className="w-3.5 h-3.5 text-slate-500" />
                          <a href={`tel:${match.lost_item.owner.phone}`} className="text-indigo-400 hover:underline">{match.lost_item.owner.phone}</a>
                        </p>
                      </div>
                    </div>

                    {/* Found Finder Contact details */}
                    <div className="p-4 bg-slate-900 border border-slate-800 rounded-2xl space-y-3">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 flex items-center gap-1">
                        <ShieldCheck className="w-3.5 h-3.5 text-indigo-400" />
                        <span>Finder / Claim Details</span>
                      </span>
                      <div className="text-xs space-y-1.5 text-slate-300">
                        <p className="font-bold text-slate-100">{match.found_item.finder.name}</p>
                        <p className="flex items-center gap-1.5">
                          <Mail className="w-3.5 h-3.5 text-slate-500" />
                          <a href={`mailto:${match.found_item.finder.email}`} className="text-indigo-400 hover:underline">{match.found_item.finder.email}</a>
                        </p>
                        <p className="flex items-center gap-1.5">
                          <Phone className="w-3.5 h-3.5 text-slate-500" />
                          <a href={`tel:${match.found_item.finder.phone}`} className="text-indigo-400 hover:underline">{match.found_item.finder.phone}</a>
                        </p>
                      </div>
                    </div>

                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
export default Matches;
